// apps/site/src/components/CardSearch.svelte
<script lang="ts">
/**
 * The card search field, and the results under it — the surface `docs/PLAN.md`
 * Phase 2 calls the product.
 *
 * `docs/DESIGN.md`: "The search field is the hero. No marketing hero, no
 * illustration above the fold. The first thing on the page is the thing you
 * came to do." This is `RulesSearch.svelte`'s sibling and follows it
 * deliberately and closely — same URL contract, same degradation story, same
 * live-region timing, same row idiom — because two search fields on one site
 * that behave differently are two things to learn.
 *
 * FOUR THINGS IT HAS TO GET RIGHT.
 *
 * 1. **Every view is a URL.** `/search?q=banned:cc` is a real address that
 *    renders those results: the query is read from the URL on load, written
 *    back as you type (`replaceState`, so the back button is not filled with
 *    keystrokes) and pushed on submit.
 * 2. **The form degrades to a static browse; live results need JavaScript.**
 *    The form is a real `GET` to `/cards`, so a browser with no islands
 *    running still produces a shareable URL and still reaches every
 *    `/card/<slug>` page. What it cannot do is answer the query — the ranking
 *    runs here, and a static build has no server. The page says so in a
 *    `NoScriptNotice` above the field rather than letting a submitted query
 *    vanish in silence.
 * 3. **Nothing here composes prose.** Every string a reader sees is either a
 *    verbatim card value, an identifier, or interface wording written by a
 *    person and checked in. `docs/PLAN.md`: no language model in the shipped
 *    product.
 * 4. **NO LEGALITY VERDICT APPEARS ON A ROW.** A pill reading "Banned" needs a
 *    format attached to mean anything, and a row has six of them. The verdict
 *    is per-format, dated and evidenced, and it lives on the card page — which
 *    is the page the reader is choosing between anyway. `legal:cc` and
 *    `banned:cc` filter *by* it, so the question is answerable without the
 *    surface making an unqualified claim.
 *
 * COMPOSED, NOT RESTYLED. The field, the jewel on every row, the plate and the
 * rule under it are all `optfall-components` primitives. This file used to
 * carry its own copy of the search form and its styles, alongside a note that
 * they were being kept byte-identical against the day somebody extracted them;
 * `SearchField` is that extraction, and the styles were lifted verbatim rather
 * than rewritten so the reasoning attached to each rule came with it. What is
 * left here is the rhythm of a result row and the grid — `ResultRow` and
 * `ResultGrid` are the primitives this file now records as missing.
 *
 * A NOTE FOR THE NEXT PERSON EDITING THIS COMMENT: do not write the literal
 * opening style tag anywhere in this script, in prose or in backticks. Astro's
 * Svelte tooling locates the style block by scanning for that tag rather than
 * by parsing, so a mention of it inside a comment makes it treat the rest of
 * the file as CSS — and `astro check` then reports the component as
 * unparseable from the pages that import it, with no indication that a comment
 * is the cause.
 */
import {
  BevelledPlate,
  CardFace,
  OrnamentalRule,
  PitchJewel,
  /*
   * IT WAS USED AND NEVER IMPORTED, AND THAT SHIPPED.
   *
   * `<ResultRow>` has been in this template since list mode existed, with no
   * import to resolve it, so hydrating `/search?display=list` threw
   * `ReferenceError: ResultRow is not defined` and the island rendered
   * nothing at all — on the live site, not only here.
   *
   * Nothing in the pipeline was going to say so. `astro check` reports on
   * `.astro` files and does not resolve identifiers inside a Svelte
   * template; `astro build` compiles the island rather than mounting it, so
   * an undefined component is a runtime lookup that never runs at build
   * time; and the test suite exercises `card-search.ts`, which is the engine
   * and not the view. Every gate was green over a view that could not mount.
   *
   * It was found by opening the page. That is the whole lesson, and it is
   * the same one `check-dev-server.ts` was written for: a build that
   * succeeds is not evidence that anything renders.
   */
  ResultRow,
  SearchField,
} from "optfall-components/svelte";

import { boxFor, faceUrl, placeholderUrl } from "../lib/faces";

import {
  CARD_RESULT_LIMIT,
  decodeCardIndex,
  searchCards,
  type CardDisplayMode,
  type CardMatchField,
  type EncodedCardIndex,
} from "../lib/card-search";

interface Props {
  /** Built at build time by `buildCardIndex`; see `card-search.ts`. */
  index: EncodedCardIndex;
  /** Spend the screen's one filigree on this component's section rule. */
  ornament?: boolean;
}

const { index, ornament = false }: Props = $props();

/**
 * Decoded once — `$derived`, not `$state` and not a bare call. Same reasoning
 * as `RulesSearch.svelte`: the index is immutable data, so making it reactive
 * would put a hundred thousand strings through a proxy for nothing, and
 * reading a prop during initialisation captures its value at that instant.
 */
const cards = $derived(decodeCardIndex(index));

function queryFromUrl(): string {
  if (typeof window === "undefined") return "";
  return new URLSearchParams(window.location.search).get("q") ?? "";
}

/**
 * TWO PIECES OF STATE, AND THE SPLIT IS THE WHOLE INTERACTION MODEL.
 *
 * `query` is what is in the box. `submitted` is what has been asked. Results
 * derive from `submitted`, so nothing re-ranks while somebody is still
 * typing — `docs/SCRYFALL-GAP.md` §5.2, which settled that search here is
 * submit-driven rather than live, for reasons beyond imitating Scryfall:
 *
 * - A grid of card faces reflowing under the cursor on every keystroke is
 *   noise, and it makes the image layer fight the search layer for bandwidth.
 * - The URL is the product, and a submit is the moment a query becomes a link
 *   worth pasting. Live filtering blurs the point at which that happens.
 * - It deletes the debounce, the race handling and the partial-query ranking
 *   path outright, rather than tuning them.
 * - The no-JS path stops being a special case: the form is a real GET to this
 *   same address, so the difference between scripting on and off narrows to
 *   who renders the list rather than whether the page works.
 */
let query = $state(queryFromUrl());
let submitted = $state(queryFromUrl());
let field = $state<HTMLInputElement | null>(null);

const outcome = $derived(searchCards(cards, submitted));
const asked = $derived(submitted.trim() !== "");
const truncated = $derived(outcome.total > outcome.results.length);

/**
 * How results are shown. In the URL like everything else, so a pasted link
 * carries the view its sender was looking at.
 *
 * The grid is the default because the face is the fastest way to recognise a
 * card. The list is the dense row this component already had — it is not
 * thrown away, it is a mode, and it stays better than Scryfall's checklist
 * because it carries the stat line and the reason the row matched.
 */
function displayFromUrl(): CardDisplayMode | null {
  if (typeof window === "undefined") return null;
  const wanted = new URLSearchParams(window.location.search).get("display");
  if (wanted === "list") return "list";
  if (wanted === "text" || wanted === "checklist") return "text";
  if (wanted === "grid") return "grid";
  return null;
}

/**
 * `display:` IS A QUERY TERM NOW, AND THE PARAMETER IS WHAT IT REPLACED.
 *
 * §5.2: every piece of state is in the URL, and `display:` belongs in the
 * query "rather than as UI chrome". So the mode is read off the parsed query
 * first — and only where the query says nothing does the old `?display=`
 * parameter get a vote.
 *
 * That order is the whole of the backwards compatibility story. Links shared
 * before this existed carry `?display=list` and keep working; links shared
 * after carry it in `q` and win over a stale parameter if somehow both are
 * present. Neither case needs the reader to know which era their link is
 * from.
 */
let paramDisplay = $state(displayFromUrl());
const display = $derived(outcome.display ?? paramDisplay ?? "grid");

/** Wording for the live region and the count line. Written, never generated. */
function summarise(): string {
  if (!asked) return "";
  if (outcome.total === 0) return `Nothing matches ${submitted.trim()}.`;
  const found = `${outcome.total} card${outcome.total === 1 ? "" : "s"}`;
  const shown = truncated ? `, showing the first ${CARD_RESULT_LIMIT}` : "";
  return `${found} match${outcome.total === 1 ? "es" : ""}${shown}.`;
}

const summary = $derived(summarise());

/**
 * The live region can speak immediately now, and that is a direct dividend of
 * the submit-driven model above.
 *
 * This used to debounce by 600ms, because results changed on every keystroke
 * and announcing each one would make a screen reader unusable — every
 * interruption cancels the last. Results now change only when somebody asks,
 * so there is exactly one announcement per query and nothing to settle. The
 * timer is gone rather than tuned.
 */
const announcement = $derived(summary);

/**
 * `written` is what the URL should say, and it is NOT always the box.
 *
 * A submit writes what was just asked; switching Grid/List writes what is
 * *currently answered*. Both were writing `query`, so typing a new query
 * without submitting and then toggling the view pushed a URL carrying the
 * un-submitted text while the screen showed results for the old one —
 * reloading or sharing that link then showed something different from what
 * was on screen.
 */
function syncUrl(mode: "replace" | "push", written: string = submitted): void {
  if (typeof window === "undefined") return;
  const url = new URL(window.location.href);
  const trimmed = written.trim();
  if (trimmed === "") url.searchParams.delete("q");
  else url.searchParams.set("q", written);
  /* THE PARAMETER IS NEVER WRITTEN AGAIN, only read. The mode travels inside
       `q` now, so writing it in both places would produce URLs that can
       disagree with themselves — and a stale `?display=list` beside a
       `display:text` query is exactly the ambiguity this operator removed. Any
       parameter already in the address is dropped as soon as the query says
       anything, which is what the delete below does. */
  if (outcome.display !== null) url.searchParams.delete("display");
  const target = `${url.pathname}${url.search}`;
  if (target === `${window.location.pathname}${window.location.search}`) return;
  if (mode === "push") window.history.pushState({}, "", target);
  else window.history.replaceState({}, "", target);
}

/** Back and forward have to work, which means listening for them. */
$effect(() => {
  const onPop = () => {
    query = queryFromUrl();
    submitted = query;
    paramDisplay = displayFromUrl();
  };
  window.addEventListener("popstate", onPop);
  return () => window.removeEventListener("popstate", onPop);
});

/**
 * `/` focuses the field, the way every reference tool worth using does.
 * Ignored while the caret is already in a control, so it can never eat a
 * character somebody meant to type.
 */
$effect(() => {
  const onKey = (event: KeyboardEvent) => {
    if (event.key !== "/" || event.metaKey || event.ctrlKey || event.altKey)
      return;
    const target = event.target as HTMLElement | null;
    const tag = target?.tagName.toLowerCase();
    if (tag === "input" || tag === "textarea" || tag === "select") return;
    if (target?.isContentEditable) return;
    event.preventDefault();
    field?.focus();
  };
  window.addEventListener("keydown", onKey);
  return () => window.removeEventListener("keydown", onKey);
});

function onSubmit(event: SubmitEvent): void {
  event.preventDefault();
  submitted = query;
  syncUrl("push", query);
  field?.blur();

  /*
      ONE RESULT IS NOT A RESULT SET, IT IS THE ANSWER — the same behaviour
      Scryfall has, and for the same reason: a page whose entire content is a
      single row asking to be clicked has made the reader press twice for one
      destination.

      Deliberately only on SUBMIT. Arriving at a pasted `/search?q=…` link does
      NOT redirect, because the sender chose to share a search and silently
      turning it into a card page would rewrite what they sent. And the URL is
      pushed first, so the back button returns to the results rather than to
      whatever came before them.
    */
  const only = outcome.total === 1 ? outcome.results[0] : undefined;
  if (only) window.location.assign(only.href);
}

/**
 * Switching view rewrites the QUERY, because the view is part of the query.
 *
 * The control and the syntax are two ways of saying one thing, so clicking
 * "Text" has to leave the box reading `dominate display:text` — otherwise
 * the reader copies what is on screen and gets a link that does not
 * reproduce what they were looking at.
 *
 * Any existing `display:` term is replaced rather than appended: a query
 * carrying two of them would apply the last and silently ignore the first.
 * The default is written out rather than left implicit, because a reader who
 * deliberately clicked back to Grid on a `display:text` query has made a
 * choice, and dropping the term would restore text on reload.
 */
function show(next: CardDisplayMode): void {
  const withoutMode = submitted.replace(/(^|\s)display:\S+/gi, "$1").trim();
  const written = `${withoutMode} display:${next}`.trim();
  query = written;
  submitted = written;
  paramDisplay = null;
  syncUrl("push", written);
}

function onKeydown(event: KeyboardEvent): void {
  if (event.key === "Escape" && query !== "") {
    event.preventDefault();
    query = "";
  }
}

/** Why a row is on the page, in the words of the ranking that put it there. */
const WHY: Record<CardMatchField, string> = {
  "name-exact": "exact name",
  "name-prefix": "name starts with",
  name: "name",
  type: "type line",
  keyword: "keyword",
  text: "card text",
  filter: "filter",
};

const uid = $props.id();
</script>

<SearchField
  label="Search the cards"
  region="Flesh and Blood cards"
  action="/search"
  placeholder="command and conquer"
  bind:value={query}
  bind:element={field}
  onsubmit={onSubmit}
  onkeydown={onKeydown}
>
  <!--
    THE PAGE'S ONE HINT LINE, AND IT IS NOW THREE EXAMPLES AND A LINK.

    `docs/DESIGN.md` Screen 1 asks it to pair an operator people already know
    from Card Vault with one of ours, so the extension is discovered where
    fluency already exists. Three examples still do that — the first is Card
    Vault's, the second is ours, the third is the one nobody guesses.

    What it stopped doing is teaching the grammar in a paragraph. The old line
    also carried the dated-legality limit and the `/` shortcut, which made it
    the longest single block of preamble above the results and still left every
    other operator undocumented. Those facts did not become less true; they
    moved to `/syntax`, which can hold all of them, and the limit in particular
    is stated there in its own section rather than as a clause. A hint is a
    doorway, not a manual — and there was no manual to point at until now, which
    is exactly why this line had grown into one.

    Inline elements stay on the same source line as the text around them: the
    build compresses this HTML and drops the whitespace at a line break falling
    immediately before an inline tag, welding words together in the output.
  -->
  {#snippet hint()}
    <code>pitch:3 class:guardian</code> · <code>banned:cc</code> · <code>text:dominate</code> — <a href="/syntax">all operators</a>
  {/snippet}
</SearchField>

<!-- Always present, never emptied: a live region added to the page at the
     moment it has something to say is a live region that says nothing. -->
<p class="announcement" role="status" aria-live="polite">{announcement}</p>

{#if outcome.notices.length > 0}
  <ul class="notices">
    {#each outcome.notices as notice (notice.kind + notice.text)}
      <!-- The wording is the engine's, not this component's: a notice is a
           statement about what the query engine did, and a surface free to
           rephrase it is a surface free to describe behaviour it does not
           have. See `CardNotice` in `card-search.ts`. -->
      <li class="notice">{notice.text}</li>
    {/each}
  </ul>
{/if}

<OrnamentalRule {ornament} label={asked ? "Results" : "Browse"} />

{#if asked}
  {#if outcome.results.length > 0}
    <div class="result-head">
      <p class="count">{summary}</p>

      <!--
        Two views of the same answer. A radio group rather than a pair of
        buttons, because that is what "pick exactly one" is, and it gets arrow
        keys and a group name for free.
      -->
      <fieldset class="views">
        <legend class="views-legend">Show results as</legend>
        {#each [["grid", "Grid"], ["list", "List"], ["text", "Text"]] as const as [mode, label] (mode)}
          <label class="view">
            <input
              type="radio"
              name="display"
              value={mode}
              checked={display === mode}
              onchange={() => show(mode)}
            />
            <span>{label}</span>
          </label>
        {/each}
      </fieldset>
    </div>

    {#if display === "grid"}
      <!--
        The face is the row. `docs/SCRYFALL-GAP.md`: results are images by
        default, because recognising a card by its face is faster than reading
        its name — which is the single largest difference between this and every
        text-list card tool in the game.

        `CardFace` carries the copyright line on every one of these, and that is
        not negotiable: COMPLIANCE.md §5 forbids a variant that drops it.
      -->
      <ul class="grid">
        {#each outcome.results as result (result.href)}
          {@const box = boxFor("thumb", result.faceLandscape ? "landscape" : "portrait")}
          <li class="cell">
            <a class="cell-link" href={result.href}>
              <CardFace
                src={result.faceKey === null
                  ? placeholderUrl(result.faceLandscape ? "landscape" : "portrait")
                  : faceUrl(result.faceKey, "thumb")}
                alt={`${result.label} — ${result.typeLine}`}
                width={box.width}
                height={box.height}
              />
              <span class="cell-name">{result.label}</span>
              {#if result.matchedPitches.length < result.totalVersions}
                <!--
                  ONLY SOME PITCH VERSIONS MATCHED, AND SAYING SO IS NOT
                  OPTIONAL. Four names in this corpus carry versions whose
                  Classic Constructed ban differs — Electromagnetic Somersault
                  red and yellow are banned, blue is legal. A `banned:cc` row
                  that named the card and stopped would be putting a card on a
                  banned list without saying which version was banned, which is
                  the "collapses two true facts into one" failure the verdict
                  model exists to prevent.
                -->
                <span class="cell-versions">
                  {result.matchedPitches
                    .map((pitch) => (pitch === 0 ? "no pitch" : `pitch ${pitch}`))
                    .join(", ")}
                </span>
              {/if}
            </a>
          </li>
        {/each}
      </ul>
    {:else if display === "list"}
    <!--
      NAMED RATHER THAN LEFT AS `{:else}`, because there are three modes now
      and "not grid" stopped meaning "list" the moment the third one existed.
      An open else here rendered the dense row for `display:text` as well —
      and then the text list rendered underneath it, so the page showed both.
    -->
    <ol class="results">
      {#each outcome.results as result (result.href)}
        <ResultRow href={result.href} label={result.label}>
          {#snippet lead()}
            <PitchJewel value={result.pitch} size="sm" />
          {/snippet}
          {#snippet meta()}
            <!--
              `result.label` above, never the bare name: 900 names in this
              corpus belong to two to four different cards, and a list of
              anchors reading "Head Jab" three times against three destinations
              is a WCAG 2.4.4 failure as well as being useless. `ResultRow`
              takes the label as a STRING rather than a snippet for exactly
              that reason — the accessible name has to be composed on purpose.
            -->
            <span>{result.typeLine}</span>
            {#each result.stats as [label, value] (label)}
              <span>{label} {value}</span>
            {/each}
            {#if result.matchedPitches.length < result.totalVersions}
              <span>
                {result.matchedPitches
                  .map((pitch) => (pitch === 0 ? "no pitch" : `pitch ${pitch}`))
                  .join(", ")}
              </span>
            {/if}
            <span class="why">{WHY[result.matchedIn]}</span>
          {/snippet}
        </ResultRow>
      {/each}
    </ol>
    {/if}
    {#if display === "text"}
    <!--
      NAMES, ONE PER LINE, AND NOTHING ELSE.

      This is the mode that is not a denser version of the other two — it is
      the one whose output is meant to LEAVE the page. A player writing a deck
      list wants forty names they can select and paste, and every jewel, stat
      and type line in the way of that selection is a thing they have to delete
      afterwards.

      So the markup is deliberately thin: an anchor per line, no lead, no meta,
      no decoration inside the list. Each name is still a link, because a text
      list of names that cannot be clicked would be a worse version of both
      other modes rather than a different one.

      `<ol>` rather than `<ul>` to match the other two views — the order is the
      ranking, and it means something in every mode.
    -->
    <ol class="text-results">
      {#each outcome.results as result (result.href)}
        <li><a href={result.href}>{result.label}</a></li>
      {/each}
    </ol>
    {/if}
    {#if truncated}
      <p class="count">
        {outcome.total - outcome.results.length} more match. Narrow the query — every
        word you add has to appear on the card.
      </p>
    {/if}
  {:else}
    <p class="count">
      Nothing in the {cards.size.toLocaleString("en-GB")} cards matches every part of
      <strong>{submitted.trim()}</strong>. Words match whole words and the start of words,
      so <code>domin</code> finds <code>dominate</code> — but every word you type has
      to appear in the name, the type line, a keyword or the printed text.
    </p>
  {/if}
{:else}
  <p class="count">
    {cards.size.toLocaleString("en-GB")} cards, pinned to upstream commit
    <code>{cards.commit.slice(0, 7)}</code> and last confirmed {cards.confirmed}. Start
    with a type, or type above.
  </p>
  <!--
    The empty state is a browse, not a blank rectangle — and it is derived from
    the corpus rather than curated, so it cannot go stale and cannot express an
    opinion about which types matter. The count beside each is the real number
    of cards carrying that printed type line.
  -->
  <ul class="browse">
    {#each cards.browse as [line, count] (line)}
      <li>
        <a class="browse-link" href={`/search?q=${encodeURIComponent(`type:"${line}"`)}`}>
          {line}
        </a>
        <span class="browse-count">{count}</span>
      </li>
    {/each}
  </ul>
{/if}

<style>
  /* -- Result head: the count, and the view switch ------------------------- */

  .result-head {
    display: flex;
    flex-wrap: wrap;
    align-items: baseline;
    justify-content: space-between;
    gap: var(--of-space-base);
  }

  .views {
    display: flex;
    align-items: center;
    gap: var(--of-space-base);
    margin: 0;
    padding: 0;
    border: 0;
  }

  /* The group needs a name for assistive technology and no name on screen —
     the two labels beside it already say what it does. */
  .views-legend {
    position: absolute;
    inline-size: var(--of-space-hair);
    block-size: var(--of-space-hair);
    padding: 0;
    overflow: hidden;
    clip-path: inset(50%);
    white-space: nowrap;
  }

  .view {
    display: inline-flex;
    align-items: center;
    gap: var(--of-space-tight);
    font-family: var(--of-type-family-sans);
    font-size: var(--of-type-size-micro);
    letter-spacing: var(--of-type-tracking-wide);
    text-transform: uppercase;
    color: var(--of-color-ink-muted);
    cursor: pointer;
  }

  .view:has(input:checked) {
    color: var(--of-color-ink);
  }

  /* -- The grid ------------------------------------------------------------ */

  /*
    Sized from the thumb tier so a cell is the width of the face it holds, and
    the track count follows the viewport rather than being chosen. `auto-fill`
    rather than `auto-fit` so a single result stays card-sized instead of
    stretching across the row.
  */
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(var(--of-card-face-thumb), 1fr));
    gap: var(--of-space-loose);
    margin-block-start: var(--of-space-loose);
    padding: 0;
    list-style: none;
  }

  .cell-link {
    display: flex;
    flex-direction: column;
    gap: var(--of-space-tight);
    text-decoration: none;
    color: inherit;
  }

  /*
    The name is the accessible name of the link along with the face's alt text,
    and it is visible because recognising art is not the same as being sure —
    900 names in this corpus belong to more than one card, and the variant
    suffix is what tells two identical-looking faces apart.
  */
  .cell-name {
    font-family: var(--of-type-family-serif);
    font-size: var(--of-type-size-small);
    line-height: var(--of-type-leading-tight);
    color: var(--of-color-ink);
  }

  .cell-versions {
    font-family: var(--of-type-family-sans);
    font-size: var(--of-type-size-micro);
    letter-spacing: var(--of-type-tracking-wide);
    text-transform: uppercase;
    color: var(--of-color-ink-muted);
  }

  .cell-link:hover .cell-name,
  .cell-link:focus-visible .cell-name {
    color: var(--of-color-accent);
  }

  /*
    THE PRIMITIVES THIS PAGE FOUND MISSING, exactly as `RulesSearch.svelte`
    records: a text field and a dense list row. Both are real gaps rather than
    one-off decoration, so they belong in `optfall-components` as `SearchField`
    and `ResultRow`. Kept identical to the rules search on purpose — every value
    names a token, so moving them costs a cut and a paste.
  */





  /*
    Never `outline: none`, and `:focus` rather than `:focus-visible` alone — a
    text field focused with a mouse is still a text field you are about to type
    into, and hiding that from the one input on the page would be hiding the
    state that matters most.
  */







  /*
    The announcement is for assistive technology; the same words are printed
    visibly in `.count` beside the results, so this one is off-screen rather
    than duplicated on the page. Sized from `space.hair` rather than collapsed
    to zero: a zero-area element is skipped by some screen readers.
  */
  .announcement {
    position: absolute;
    inline-size: var(--of-space-hair);
    block-size: var(--of-space-hair);
    margin: calc(var(--of-space-hair) * -1);
    padding: 0;
    border: 0;
    overflow: hidden;
    clip-path: inset(50%);
    white-space: nowrap;
  }

  .notices {
    margin-block: var(--of-space-base) 0;
    padding-inline-start: 0;
    list-style: none;
  }

  .notice {
    padding-block: var(--of-space-tightest);
    border-inline-start: calc(var(--of-bevel-width) * 2) solid var(--of-color-accent);
    padding-inline-start: var(--of-space-tight);
    color: var(--of-color-ink-muted);
    font-size: var(--of-type-size-small);
  }

  .count {
    margin-block: 0 var(--of-space-base);
    color: var(--of-color-ink-muted);
    font-size: var(--of-type-size-small);
  }

  /*
    A LIST THAT IS MEANT TO BE COPIED. No markers, no padding on the items,
    tight leading — so a drag-select over it yields the names and nothing that
    has to be cleaned out of the paste afterwards.
  */
  .text-results {
    list-style: none;
    margin: var(--of-space-loose) 0 0;
    padding: 0;
    display: grid;
    gap: var(--of-space-hair);
    font-size: var(--of-type-size-small);
  }

  .text-results a {
    color: var(--of-color-ink);
    text-decoration: none;
  }

  .text-results a:hover,
  .text-results a:focus-visible {
    text-decoration: underline;
  }

  .results {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  /*
    Density without clutter: rows are separated by one hairline and nothing else
    — no card, no shadow, no padding a reader has to look past. The row wraps
    intrinsically rather than at a breakpoint, since the theme publishes no
    breakpoint tokens and a raw one is not available to write.
  */



  /* Serif — the voice assigned to names. */



  .browse {
    display: grid;
    gap: var(--of-space-tight);
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .browse li {
    display: flex;
    flex-wrap: wrap;
    align-items: baseline;
    justify-content: space-between;
    gap: var(--of-space-base);
    padding-block: var(--of-space-tight);
    border-block-start: var(--of-ornament-rule-width) solid var(--of-color-rule);
  }

  .browse-link {
    font-family: var(--of-type-family-sans);
    font-size: var(--of-type-size-small);
    letter-spacing: var(--of-type-tracking-wide);
  }

  .browse-count {
    font-family: var(--of-type-family-sans);
    font-size: var(--of-type-size-micro);
    letter-spacing: var(--of-type-tracking-wide);
    color: var(--of-color-ink-faint);
  }
</style>

// apps/site/ssg/islands/CardSearch.tsx
/**
 * The card search field, and the results under it. React port.
 *
 * SUBMIT-DRIVEN, NOT LIVE, and that is the load-bearing difference from
 * `RulesSearch`. `docs/SCRYFALL-GAP.md` §5.2: results do NOT re-rank on every
 * keystroke. A grid of card faces reflowing under a cursor is noise, it makes
 * the image layer fight the search layer for bandwidth, and the URL is the
 * product — a submit is the moment a query becomes a link worth pasting, and
 * live filtering blurs the point at which that happens.
 *
 * That is why there are two pieces of state rather than one: `query` is what is
 * in the box, `submitted` is what the results answer. The rules search has one,
 * because it is live.
 *
 * ONE RESULT IS NOT A RESULT SET, IT IS THE ANSWER — the same behaviour Scryfall
 * has, and for the same reason: a page whose entire content is a single row
 * asking to be clicked has made the reader press twice for one destination.
 * Deliberately only on SUBMIT: arriving at a pasted `/search?q=…` link does NOT
 * redirect, because the sender chose to share a search and silently turning it
 * into a card page would rewrite what they sent.
 *
 * `display:` IS A QUERY TERM, and `?display=` is only read. The mode is taken
 * from the parsed query first; the legacy parameter gets a vote only where the
 * query says nothing. Writing it in both places would produce URLs that
 * contradict themselves.
 *
 * THE URL IS READ IN AN EFFECT, NOT AT INITIALISATION, for the reason
 * `RulesSearch` records at length: the server has no `window`, so initialising
 * from `?q=` renders a different tree than the server did and hydration fails
 * with React error #418.
 *
 * THE PAGE IS PART OF THE ADDRESS, not part of this component's state — `?page=`
 * and `?per=`, read on mount and on `popstate` exactly as `?q=` is, written on
 * every deliberate act exactly as `?q=` is. There is no cap left anywhere in
 * the path: `?per=all` resolves to an infinite limit and the reader is looking
 * at every row that matched. See `../../src/lib/pagination.ts`.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { OrnamentalRule, Pagination } from "optfall-components/react";

import {
  type CardDisplayMode,
  type CardMatchField,
  decodeCardIndex,
  type EncodedCardIndex,
  searchCards,
} from "../../src/lib/card-search";
import {
  DEFAULT_PAGE_SIZE,
  PAGE_PARAM,
  PAGE_SIZES,
  type PageSize,
  pageHref,
  paginate,
  parsePage,
  parsePageSize,
  requestFor,
  SIZE_PARAM,
  withPageParams,
} from "../../src/lib/pagination";
import { CardIndex, type CardIndexEntry } from "../components/CardIndex";

import "./CardSearch.css";

/**
 * The shell's search input, which this island drives on `/search`.
 *
 * A STRING SHARED WITH `SiteHeader.tsx` AND NOTHING ENFORCES IT, which is worth
 * saying out loud rather than hiding behind a constant. The header is rendered
 * by the document shell and this island is mounted inside `<main>`, so there is
 * no prop between them; if the id changes there and not here the field simply
 * stops being adopted — the form still submits and navigates, so the page keeps
 * working and gets slower, which is the failure mode to prefer but also the
 * kind that goes unnoticed. `ssg.test.ts` asserts the two agree.
 */
export const HEADER_FIELD_ID = "site-search";

/** Ties the header's field to the operator examples rendered on this page. */
const HINT_ID = "cards-search-hint";

export interface CardSearchProps {
  readonly index: EncodedCardIndex;
  readonly ornament?: boolean;
}

/** Why a row is on the page, in the words of the ranking that put it there. */
const WHY: Record<CardMatchField, string> = {
  "name-exact": "exact name",
  "name-prefix": "name starts with",
  name: "name",
  type: "type line",
  keyword: "keyword",
  text: "card text",
  filter: "filter",
};

function queryFromUrl(): string {
  if (typeof window === "undefined") return "";
  return new URLSearchParams(window.location.search).get("q") ?? "";
}

function displayFromUrl(): CardDisplayMode | null {
  if (typeof window === "undefined") return null;
  const wanted = new URLSearchParams(window.location.search).get("display");
  if (wanted === "list") return "list";
  if (wanted === "text" || wanted === "checklist") return "text";
  if (wanted === "grid") return "grid";
  return null;
}

/** Which page, and how many rows on it. Read from the URL, like the query. */
function pagingFromUrl(): { page: number; size: PageSize } {
  if (typeof window === "undefined")
    return { page: 1, size: DEFAULT_PAGE_SIZE };
  const params = new URLSearchParams(window.location.search);
  return {
    page: parsePage(params.get(PAGE_PARAM)),
    size: parsePageSize(params.get(SIZE_PARAM)),
  };
}

export function CardSearch({ index, ornament = false }: CardSearchProps) {
  const cards = useMemo(() => decodeCardIndex(index), [index]);

  const [query, setQuery] = useState("");
  const [submitted, setSubmitted] = useState("");
  const [page, setPage] = useState(1);
  const [size, setSize] = useState<PageSize>(DEFAULT_PAGE_SIZE);
  const [paramDisplay, setParamDisplay] = useState<CardDisplayMode | null>(
    null,
  );
  /*
    FALSE ON THE SERVER AND ON THE FIRST CLIENT RENDER. The view switch is a
    radio group and does nothing without JavaScript — a control that looks
    operable and is not. The PAGER is not gated this way and must not be: it is
    made of real links, which is what lets a page of a search be an address.
    Flipping this in an effect keeps the two first renders identical, which is
    what hydration checks.
  */
  const [interactive, setInteractive] = useState(false);
  /**
   * THE HEADER'S FIELD, NOT ONE THIS COMPONENT RENDERS.
   *
   * `docs/SCRYFALL-GAP.md` §5.2 says the front door's hero is a search field
   * and every other screen carries the header's. This page used to have both:
   * a hero field of its own, with the header's suppressed by
   * `headerSearch: false`, which meant the results page looked like a second
   * front door rather than like the rest of the site.
   *
   * So the island ADOPTS the field the shell already renders. It is a real
   * `<form action="/search" method="get">` with `id="site-search"` inside it,
   * so with no JavaScript it submits and navigates — which is exactly what
   * Scryfall does, since Scryfall renders its results on a server. With
   * JavaScript the island takes it over and the submit is answered in place,
   * as it already was.
   *
   * REACHING OUTSIDE THE ISLAND'S OWN TREE IS THE COST, and it is worth naming.
   * The header is rendered by `document.tsx` outside `<main>`, so no island can
   * contain both the field and the results; the alternatives were two islands
   * sharing a store, or a full page load per search. `id="site-search"` is the
   * contract between them, and {@link HEADER_FIELD_ID} is where it is written
   * down on this side.
   */
  const field = useRef<HTMLInputElement | null>(null);

  /*
   * THE SUBMIT HANDLER, HELD BY REF SO THE LISTENER IS WIRED ONCE.
   *
   * The DOM listener below is attached on mount and never rebound; reading
   * `query` from its closure would read the value at mount forever. A ref
   * holding the latest handler is the standard shape for that, and it keeps the
   * effect's dependency list empty — which matters here because rebinding a
   * listener on the SHELL's input every keystroke is a side effect on a node
   * this component does not own.
   *
   * **THE SUBMITTED TEXT IS PASSED IN RATHER THAN READ FROM STATE, AND THAT IS
   * A BUG THIS BRANCH ALREADY HAD.** `input` and `submit` can arrive in ONE
   * task — a paste followed by Enter, or any programmatic submit — and
   * `setQuery` only schedules a render, so the ref still holds the previous
   * render's closure when the submit handler runs. Measured: submitting a new
   * query immediately after setting the field re-ran the OLD one, left the URL
   * alone, and looked from the outside like the field had stopped working.
   *
   * So the handler takes the field's own value. That is also just what a form
   * is: at submit, the input is the truth and React state is a copy of it.
   */
  const submitRef = useRef<(raw: string) => void>(() => {});
  const escapeRef = useRef<() => void>(() => {});

  useEffect(() => {
    const input = document.getElementById(HEADER_FIELD_ID);
    if (!(input instanceof HTMLInputElement)) return;

    field.current = input;
    const form = input.form;

    /* The hint belongs to this field now, so the field has to say so. It is
       rendered on the page rather than in the shell, because the operator
       examples are about THIS page and the header is on every page. */
    const described = input.getAttribute("aria-describedby");
    input.setAttribute("aria-describedby", HINT_ID);

    const onInput = () => setQuery(input.value);
    const onSubmit = (event: Event) => {
      event.preventDefault();
      submitRef.current(input.value);
    };
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") escapeRef.current();
    };

    input.addEventListener("input", onInput);
    input.addEventListener("keydown", onKeyDown);
    form?.addEventListener("submit", onSubmit);

    return () => {
      input.removeEventListener("input", onInput);
      input.removeEventListener("keydown", onKeyDown);
      form?.removeEventListener("submit", onSubmit);
      if (described === null) input.removeAttribute("aria-describedby");
      else input.setAttribute("aria-describedby", described);
      field.current = null;
    };
  }, []);

  /*
   * THE FIELD SHOWS THE QUERY IT IS ANSWERING, which is the whole reason a
   * results page has a field in it at all.
   *
   * The header's input is server-rendered empty — it is on every page, and the
   * query lives in `?q=`, which a static document cannot know. So the value is
   * written here, from the state that `?q=` populates on mount, and rewritten
   * whenever the query changes for a reason other than typing: Escape clears
   * it, `display:` switches rewrite it, and `popstate` restores it. Without
   * this a reader lands on `/search?q=banned:cc`, sees 35 results and an EMPTY
   * box, and cannot edit the query that produced them.
   *
   * Guarded on inequality so typing does not fight the caret: the `input`
   * listener sets state from the field, and writing the same string back would
   * move the cursor to the end mid-word.
   */
  useEffect(() => {
    const input = field.current;
    if (input !== null && input.value !== query) input.value = query;
  }, [query]);

  useEffect(() => {
    setInteractive(true);
    const fromUrl = queryFromUrl();
    if (fromUrl !== "") {
      setQuery(fromUrl);
      setSubmitted(fromUrl);
    }
    const paging = pagingFromUrl();
    setPage(paging.page);
    setSize(paging.size);
    setParamDisplay(displayFromUrl());
  }, []);

  /**
   * THE QUERY RUNS TWICE ONLY FOR A PAGE PAST THE END, and never otherwise.
   *
   * The slice the URL asks for is known before the query runs; how many pages
   * there are is not. So the common path is one pass at the requested offset,
   * and the only way to get an empty page out of a non-empty answer is a `?page=`
   * beyond the last one — a stale link, where a second pass against the clamped
   * offset is worth a ranking pass to avoid answering with a blank list.
   */
  const outcome = useMemo(() => {
    const wanted = requestFor(page, size);
    const first = searchCards(cards, submitted, wanted.limit, wanted.offset);
    if (first.results.length > 0 || first.total === 0) return first;
    const clamped = paginate(first.total, page, size);
    return searchCards(cards, submitted, clamped.limit, clamped.offset);
  }, [cards, submitted, page, size]);

  const asked = submitted.trim() !== "";
  const slice = paginate(outcome.total, page, size);
  const display = outcome.display ?? paramDisplay ?? "grid";

  const summary = (() => {
    if (!asked) return "";
    if (outcome.total === 0) return `Nothing matches ${submitted.trim()}.`;
    const found = `${outcome.total} card${outcome.total === 1 ? "" : "s"}`;
    /* The RANGE is the pager's sentence; this one states the total and, when
       there is more than one page, where in it the reader is standing. Said
       here as well as there because this string is what the live region
       announces, and a screen reader that is told the count but not the page
       has been told the answer moved without being told where to. */
    const where =
      slice.pages > 1 ? ` Page ${slice.page} of ${slice.pages}.` : "";
    return `${found} match${outcome.total === 1 ? "es" : ""}.${where}`;
  })();

  /**
   * The rows, in the shape every list of cards on this site is rendered from.
   *
   * THE MAPPING IS THE WHOLE OF WHAT SEARCH ADDS. A result knows why it is on
   * the page and which versions it stands for; a set page's row knows neither
   * and carries a printing instead. Both are `CardIndexEntry`, which is what
   * makes them one rendering rather than two that look alike.
   */
  const entries: readonly CardIndexEntry[] = outcome.results.map((result) => ({
    href: result.href,
    label: result.label,
    name: result.name,
    qualifier: result.qualifier,
    typeLine: result.typeLine,
    faceKey: result.faceKey,
    faceLandscape: result.faceLandscape,
    /*
      THE MATCHED VERSIONS, NOT EVERY VERSION. A `pitch:1` search that drew
      three bands under Head Jab would be answering a question about red with a
      picture of red, yellow and blue.

      AND EACH BAND IS A DOOR TO THE VERSION IT DREW, which is the whole of what
      carrying the addresses buys: the row goes to the card, the blue band goes
      to the blue one. A filtered search keeps that honest for free — only the
      versions that matched are drawn, so only the versions that matched can be
      clicked, and `banned:cc` cannot offer a reader the legal version of a card
      it has just put on a banned list.
    */
    versions: result.matchedVersions,
    stats: result.stats,
    why: WHY[result.matchedIn],
  }));

  /**
   * `written` is what the URL should say, and it is NOT always the box.
   *
   * A submit writes what was just asked; switching the view writes what is
   * *currently answered*. Both writing `query` meant that typing a new query
   * without submitting and then toggling the view pushed a URL carrying the
   * un-submitted text while the screen showed results for the old one.
   */
  const syncUrl = useCallback(
    (
      mode: "replace" | "push",
      written: string,
      dropParam: boolean,
      nextPage: number,
      nextSize: PageSize,
    ): void => {
      if (typeof window === "undefined") return;
      const url = new URL(window.location.href);
      const trimmed = written.trim();
      if (trimmed === "") url.searchParams.delete("q");
      else url.searchParams.set("q", written);
      withPageParams(url.searchParams, nextPage, nextSize);
      /* The parameter is never written again, only read. A stale
         `?display=list` beside a `display:text` query is exactly the ambiguity
         the operator removed. */
      if (dropParam) url.searchParams.delete("display");
      const target = `${url.pathname}${url.search}`;
      if (target === `${window.location.pathname}${window.location.search}`) {
        return;
      }
      if (mode === "push") window.history.pushState({}, "", target);
      else window.history.replaceState({}, "", target);
    },
    [],
  );

  /**
   * The address of another page of THIS answer, built off the live URL.
   *
   * Off the URL rather than from `pageHref` so that everything this component
   * does not own survives the click — `?display=list` in particular, which is
   * read but never written, and which a from-scratch href would silently drop
   * and so change the view as a side effect of turning a page.
   *
   * `submitted` rather than `query`, for the reason `syncUrl`'s own comment
   * gives: the box may hold text that has not been asked yet, and a link
   * carrying it would point at a page of a search nobody has run.
   */
  const linkTo = useCallback(
    (nextPage: number, nextSize: PageSize): string => {
      /* The pager renders only under results, and results exist only after
         hydration — so this branch is unreachable in the server render rather
         than merely unused there. */
      if (typeof window === "undefined") {
        return pageHref("/search", submitted, nextPage, nextSize);
      }
      const url = new URL(window.location.href);
      if (submitted.trim() === "") url.searchParams.delete("q");
      else url.searchParams.set("q", submitted);
      withPageParams(url.searchParams, nextPage, nextSize);
      return `${url.pathname}${url.search}`;
    },
    [submitted],
  );

  /**
   * Turning a page returns the reader to the top of the results.
   *
   * The pager is BELOW the list, so a page turned in place leaves the reader
   * looking at the end of a list they have not seen the start of. No smooth
   * behaviour: this is a jump between two views of one answer, and animating it
   * would suggest the intervening rows exist.
   */
  const goTo = useCallback(
    (nextPage: number, nextSize: PageSize): void => {
      setPage(nextPage);
      setSize(nextSize);
      syncUrl("push", submitted, false, nextPage, nextSize);
      window.scrollTo({ top: 0 });
    },
    [submitted, syncUrl],
  );

  /** Back and forward have to work, which means listening for them. */
  useEffect(() => {
    const onPop = () => {
      const next = queryFromUrl();
      setQuery(next);
      setSubmitted(next);
      const paging = pagingFromUrl();
      setPage(paging.page);
      setSize(paging.size);
      setParamDisplay(displayFromUrl());
    };
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  }, []);

  /** `/` focuses the field, the way every reference tool worth using does. */
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key !== "/" || event.metaKey || event.ctrlKey || event.altKey) {
        return;
      }
      const target = event.target as HTMLElement | null;
      const tag = target?.tagName.toLowerCase();
      if (tag === "input" || tag === "textarea" || tag === "select") return;
      if (target?.isContentEditable) return;
      event.preventDefault();
      field.current?.focus();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  /**
   * Switching view rewrites the QUERY, because the view is part of the query.
   *
   * The control and the syntax are two ways of saying one thing, so clicking
   * "Text" has to leave the box reading `dominate display:text` — otherwise the
   * reader copies what is on screen and gets a link that does not reproduce what
   * they were looking at. Any existing `display:` term is replaced rather than
   * appended: two of them would apply the last and silently ignore the first.
   */
  function show(next: CardDisplayMode): void {
    const withoutMode = submitted.replace(/(^|\s)display:\S+/gi, "$1").trim();
    const written = `${withoutMode} display:${next}`.trim();
    setQuery(written);
    setSubmitted(written);
    setParamDisplay(null);
    /* THE PAGE IS KEPT, and that is the point of switching views: the rows are
       the same rows in a different shape, so a reader six pages into an answer
       who wants to read the names instead of look at the faces has not asked to
       start over. */
    syncUrl("push", written, true, page, size);
  }

  /**
   * What a submit does, lifted out of the JSX it used to live in.
   *
   * NAMED RATHER THAN INLINE BECAUSE THE FIELD IS NO LONGER OURS. The header's
   * input is a DOM node this island adopts, so the handler reaches it through
   * `submitRef` instead of through a prop — and a listener bound once on mount
   * would otherwise close over the first render's `query` forever.
   *
   * `raw` IS THE FIELD'S OWN VALUE AT SUBMIT, not `query`. See the note on
   * `submitRef`: state lags the input by a render, and the two can be read in
   * the same task.
   */
  function submitQuery(raw: string): void {
    /*
      THE NEW QUERY IS RANKED HERE, NOT READ OFF `outcome`, and that is a
      React correction rather than a detail of the port.

      `outcome` is a `useMemo` over `submitted`, so inside this handler it
      still holds the PREVIOUS query's results: `setSubmitted` schedules a
      re-render, it does not recompute anything synchronously. The Svelte
      original could read its `$derived` on the line after assigning
      because a `$derived` recomputes when read; reading the memo here is
      one submit behind.

      That staleness is not cosmetic in either place it was used. The
      redirect would send the reader to the PREVIOUS query's single match
      — asking `dominate` right after a one-result query navigates to that
      earlier card and discards what was just typed — and `display` would
      decide whether to strip the legacy `?display=` parameter from the
      previous query's parse, leaving exactly the self-contradicting URL
      the operator exists to remove.

      It does mean the index is ranked twice per submit — here, and again
      in the memo when the re-render lands. That is accepted rather than
      overlooked: `searchCards` is pure, this is a submit rather than a
      keystroke, and the alternative is caching machinery to save one pass
      over an index the same interaction already pays for once.
    */
    const next = searchCards(cards, raw, requestFor(1, size).limit);
    setQuery(raw);
    setSubmitted(raw);
    /*
      A NEW QUERY IS PAGE ONE. Keeping the page across a submit would land
      the reader on page 6 of an answer they have not seen the top of —
      and on a shorter answer, on a page that does not exist. The SIZE is
      kept, because that is a preference about how they read rather than a
      position in one particular answer.
    */
    setPage(1);
    /*
      THE LEGACY PARAMETER IS FORGOTTEN EXACTLY WHEN IT IS DROPPED, and
      those two have to be one condition rather than two.

      `paramDisplay` was cleared in `show()` and on `popstate` but not
      here, so it outlived the URL it came from: arrive at
      `?q=x&display=list`, submit `x display:text` — the parameter is
      stripped from the address bar — then submit a plain `winter`, and the
      URL says nothing about display while the retained state still
      resolves it to `list`.

      Clearing it unconditionally produces the mirror image of that bug:
      arrive at `?q=winter&display=list` and press Enter without editing,
      and `next.display` is null so the parameter STAYS in the URL while
      the cleared state falls back to `grid` — the view changes under the
      reader and now contradicts the address bar it did not leave.

      So the state is forgotten on precisely the submits that drop the
      parameter, which is the same expression `syncUrl` is given.
    */
    const droppingParam = next.display !== null;
    if (droppingParam) setParamDisplay(null);
    syncUrl("push", raw, droppingParam, 1, size);
    field.current?.blur();

    const only = next.total === 1 ? next.results[0] : undefined;
    if (only) window.location.assign(only.href);
  }

  submitRef.current = submitQuery;
  /* UNCONDITIONAL, for the same reason `submitQuery` takes its argument: a
     guard on `query` reads state that may lag the field by a render, and
     "clear a field that is already empty" costs nothing. */
  escapeRef.current = () => {
    setQuery("");
    if (field.current !== null) field.current.value = "";
  };

  return (
    <>
      {/*
        THE HINT STAYS ON THE PAGE, THE FIELD DOES NOT.

        Three example queries and a link to the grammar. It belonged to the hero
        field and is described BY the header's field now — the adoption effect
        points `aria-describedby` at this element — because the examples are
        about what this page can be asked, and the header is on every page.
      */}
      <p className="of-search__hint of-cards__hint" id={HINT_ID}>
        <code>pitch:3 class:guardian</code> · <code>banned:cc</code> ·{" "}
        <code>text:dominate</code> — <a href="/syntax">all operators</a>
      </p>

      {/* Always present, never emptied. */}
      <p className="of-cards__announcement" role="status" aria-live="polite">
        {summary}
      </p>

      {outcome.notices.length > 0 ? (
        <ul className="of-cards__notices">
          {outcome.notices.map((notice) => (
            <li className="of-cards__notice" key={notice.kind + notice.text}>
              {notice.text}
            </li>
          ))}
        </ul>
      ) : null}

      <OrnamentalRule
        ornament={ornament}
        label={asked ? "Results" : "Browse"}
      />

      {asked ? (
        outcome.results.length > 0 ? (
          <>
            {/*
              EVERY LIST OF CARDS ON THIS SITE IS THIS COMPONENT, and search is
              one of its two callers rather than the only place a card grid
              exists. What was a hundred lines of grid, rows and names markup
              here is a mapping from `CardResult` to `CardIndexEntry` — see
              `entries` below — and the pager is handed in as a slot, because
              only this surface knows that a page of a search is
              `?q=…&page=…&per=…`.

              THE DISPLAY MODE STAYS HERE, because on this page it lives in the
              QUERY. `display:text` is a search operator, so clicking "Names"
              has to rewrite the box; a component that owned the mode would have
              no way to know that and the URL would stop reproducing the screen.
            */}
            <CardIndex
              entries={entries}
              display={display}
              onDisplayChange={show}
              summary={summary}
              controlName="display"
              interactive={interactive}
              pagination={
                /*
                  WHERE "N MORE MATCH. NARROW THE QUERY." USED TO BE.

                  That line counted rows it then refused to show, which
                  `docs/SCRYFALL-GAP.md` §4 named as the thing to delete: "a
                  refusal where Scryfall paginates. A grid makes it worse — 60
                  images is under one scroll." The count was never the problem
                  and it has not moved; what is new is that the rows it counts
                  are reachable, and that "all of them" is one of the things a
                  reader can ask for.

                  CHANGING THE SIZE GOES BACK TO PAGE ONE, because a page number
                  does not survive the change: page 4 of 60-row pages and page 4
                  of 240-row pages are different rows of the same answer, and
                  there is no reading of "4" that is true of both. Page one is
                  the one page that means the same thing at every size.
                */
                slice.needed ? (
                  <Pagination
                    from={slice.from}
                    href={(next) => linkTo(next, size)}
                    label="Pages of card results"
                    onNavigate={(next) => goTo(next, size)}
                    onResize={(next) => goTo(1, next)}
                    page={slice.page}
                    pages={slice.pages}
                    size={slice.size}
                    sizeHref={(next) => linkTo(1, next)}
                    sizes={PAGE_SIZES}
                    to={slice.to}
                    total={slice.total}
                    unit="cards"
                  />
                ) : null
              }
            />
          </>
        ) : (
          <p className="of-cards__count">
            Nothing in the {cards.size.toLocaleString("en-GB")} cards matches
            every part of <strong>{submitted.trim()}</strong>. Words match whole
            words and the start of words, so <code>domin</code> finds{" "}
            <code>dominate</code> — but every word you type has to appear in the
            name, the type line, a keyword or the printed text.
          </p>
        )
      ) : (
        <>
          <p className="of-cards__count">
            {cards.size.toLocaleString("en-GB")} cards, pinned to upstream
            commit <code>{cards.commit.slice(0, 7)}</code> and last confirmed{" "}
            {cards.confirmed}. Start with a type, or type above.
          </p>
          {/*
            The empty state is a browse, not a blank rectangle — and it is
            derived from the corpus rather than curated, so it cannot go stale
            and cannot express an opinion about which types matter. The count
            beside each is the real number of cards carrying that printed type
            line.
          */}
          <ul className="of-cards__browse">
            {cards.browse.map(([line, count]) => (
              <li key={line}>
                <a
                  className="of-cards__browse-link"
                  href={`/search?q=${encodeURIComponent(`type:"${line}"`)}`}
                >
                  {line}
                </a>
                <span className="of-cards__browse-count">{count}</span>
              </li>
            ))}
          </ul>
        </>
      )}
    </>
  );
}
