// apps/site/src/components/PrintingPicker.svelte
<script lang="ts">
  /**
   * The alternate printings of one card, as a picker that swaps the face.
   *
   * WHAT THIS REPLACES. A rail of thumbnails labelled by collector number and
   * nothing else — not clickable, so the only way to see another printing's art
   * was to not see it. A card averages 3.3 printings and several are visually
   * different (rainbow foil, cold foil, alternate art); showing them as
   * inert tiles was showing that they exist rather than showing them.
   *
   * NAMED BY SET AND NUMBER, because `BEN010` alone answers "which printing" for
   * somebody who already knows the set codes and nobody else. "Bright Lights ·
   * BEN010" answers it for everybody, and the number is kept because it is the
   * citable identity of a printing.
   *
   * WHY THIS IS AN ISLAND WHEN ALMOST NOTHING HERE IS. `docs/SCRYFALL-GAP.md`
   * §5.2 rules out live updating for SEARCH — results must not re-rank under a
   * cursor, because the URL is the product and a submit is what makes a query
   * worth pasting. A printing picker is the opposite case: it changes which
   * image is displayed and nothing else. There is no query, no ranking, no
   * result set, and nothing a reader would want to paste that the card's own
   * URL does not already carry.
   *
   * THE FACE IS SWAPPED, NOT NAVIGATED, and that is the one thing worth arguing
   * with. Per-printing URLs are still the better long-term answer — they are in
   * the plan, and they would make an individual printing linkable. Until they
   * exist, a swap is strictly better than a dead tile: the reader sees the art,
   * and the card's own permalink still resolves to the card.
   *
   * ONE SELECTION, AND IT IS A RADIO GROUP, because that is what "pick exactly
   * one of these" is. Arrow keys and a group name come free, the current choice
   * is announced rather than merely outlined, and a reader who cannot see the
   * accent border still knows which printing they are looking at.
   */
  import { CardFace, CardFaceGroup } from "optfall-components/svelte";

  interface Printing {
    /** Blob key, already resolved by the build. */
    readonly key: string;
    /** Collector number — the citable identity. Carries the edition too
     *  where set and number alone do not tell two printings apart. */
    readonly id: string;
    readonly edition: string;
    /** The set's published name, or its code where upstream names none. */
    readonly setName: string;
    readonly setCode: string;
    readonly thumb: string;
    readonly normal: string;
    readonly width: number;
    readonly height: number;
    readonly thumbWidth: number;
    readonly thumbHeight: number;
  }

  interface Props {
    printings: readonly Printing[];
    /** The accessible name for the card's picture, composed by the caller. */
    alt: string;
    /** The card's label, for the group's accessible name. */
    label: string;
  }

  const { printings, alt, label }: Props = $props();

  /**
   * WHICH PRINTING, IN THE URL — so "the rainbow foil one" is a thing you can
   * paste.
   *
   * `docs/DESIGN.md`: "Every view is a URL. Scryfall's real product is the link
   * you paste into a conversation to settle it." A picker whose selection lived
   * only in component state was a view with no address: you could find the cold
   * foil printing and then had no way to show it to anybody.
   *
   * THE PARAM IS THE FACE KEY, minus its extension — `?printing=U-WTR098`. It
   * is upstream's own art filename stem, it is unique per distinct image
   * (asserted over the corpus in `faces.test.ts`), and it survives a set
   * printing the same collector number twice: `WTR098` and `U-WTR098` are the
   * Alpha and Unlimited arts, which `WTR098` alone could not tell apart.
   *
   * AN UNKNOWN OR ABSENT PARAM FALLS BACK TO THE DEFAULT rather than erroring.
   * A stale link from before a re-sync should show the card, not a broken page
   * — the reader asked for a card and one of its printings is a better answer
   * than none.
   */
  const PARAM = "printing";

  function keyOf(printing: Printing): string {
    return printing.key.replace(/\.webp$/, "");
  }

  function selectedFromUrl(): number {
    if (typeof window === "undefined") return 0;
    const wanted = new URLSearchParams(window.location.search).get(PARAM);
    if (wanted === null) return 0;
    const index = printings.findIndex((printing) => keyOf(printing) === wanted);
    return index === -1 ? 0 : index;
  }

  let selected = $state(selectedFromUrl());
  const current = $derived(printings[selected] ?? printings[0]);

  /**
   * `replaceState`, not `pushState`.
   *
   * Clicking through six printings should not put six entries in the back
   * button — the reader is looking at one card, not visiting six pages. The
   * address stays correct so it can be copied at any moment, and Back still
   * returns to wherever they came from.
   */
  function remember(index: number): void {
    selected = index;
    if (typeof window === "undefined") return;
    const printing = printings[index];
    if (printing === undefined) return;

    const url = new URL(window.location.href);
    // The default printing is not named in the URL: a link should carry what
    // somebody chose, not restate what they did not.
    if (index === 0) url.searchParams.delete(PARAM);
    else url.searchParams.set(PARAM, keyOf(printing));
    window.history.replaceState({}, "", `${url.pathname}${url.search}`);
  }

  /** Back and forward have to work, which means listening for them. */
  $effect(() => {
    const onPop = () => {
      selected = selectedFromUrl();
    };
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  });

  const uid = $props.id();
</script>

{#if current}
  <!--
    EVERY FACE HERE GOES THROUGH THE COMPONENT, thumbnails included. An earlier
    version of this file rendered the tiles as bare `<img>` tags, which is the
    exact path docs/COMPLIANCE.md §5 names as a way to break the copyright
    condition — and it left 22 card images on a page under one notice.

    The group carries the notice for all of them, once, because these are eight
    pictures of ONE card and the legal fact is the same for each.
  -->
  <CardFaceGroup>
    <div class="picker">
    <CardFace
      src={current.normal}
      {alt}
      width={current.width}
      height={current.height}
      loading="eager"
    />

    {#if printings.length > 1}
      <fieldset class="rail">
        <legend class="rail-legend">Printings of {label}</legend>
        <ul class="rail-list">
          {#each printings as printing, index (printing.key)}
            <li>
              <label class="tile" class:current={index === selected}>
                <input
                  type="radio"
                  name={`${uid}-printing`}
                  checked={index === selected}
                  onchange={() => remember(index)}
                />
                <span class="tile-face">
                  <CardFace
                    src={printing.thumb}
                    alt=""
                    width={printing.thumbWidth}
                    height={printing.thumbHeight}
                  />
                </span>
                <span class="tile-set">{printing.setName}</span>
                <span class="tile-id">{printing.id}</span>
              </label>
            </li>
          {/each}
        </ul>
      </fieldset>
    {/if}
    </div>
  </CardFaceGroup>
{/if}

<style>
  .picker {
    display: flex;
    flex-direction: column;
    gap: var(--of-space-loose);
    max-inline-size: fit-content;
  }

  .rail {
    margin: 0;
    padding: 0;
    border: 0;
  }

  /* Named for assistive technology, unnamed on screen: the tiles say what they
     are, and a visible "Printings of Head Jab" above them would repeat the
     heading two rows up. */
  .rail-legend {
    position: absolute;
    inline-size: var(--of-space-hair);
    block-size: var(--of-space-hair);
    padding: 0;
    overflow: hidden;
    clip-path: inset(50%);
    white-space: nowrap;
  }

  .rail-list {
    display: flex;
    flex-wrap: wrap;
    gap: var(--of-space-base);
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .tile {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--of-space-tightest);
    cursor: pointer;
    color: var(--of-color-ink-muted);
  }

  /* The input is the control and the label is the target, so the radio itself
     is removed from view rather than from the accessibility tree — it still
     takes focus, still answers arrow keys, still announces its state. */
  .tile input {
    position: absolute;
    opacity: 0;
    inline-size: var(--of-space-hair);
    block-size: var(--of-space-hair);
  }

  /* The selected outline goes on the wrapper: `CardFace` owns how a face is
     drawn, and reaching past it to restyle the image would be the page
     restyling a primitive. */
  .tile-face {
    display: block;
    outline: var(--of-bevel-width) solid var(--of-color-rule);
  }

  .tile:hover {
    color: var(--of-color-ink);
  }

  /*
    The selected tile is marked by ink AND an accent edge — two channels,
    because "which printing am I looking at" is the only question this control
    exists to answer.
  */
  .tile.current {
    color: var(--of-color-ink);
  }

  .tile.current .tile-face {
    outline-color: var(--of-color-accent);
  }

  /* Focus lands on the hidden radio, so the ring is drawn on the tile it
     controls — never removed, only relocated. */
  .tile:has(input:focus-visible) .tile-face {
    outline: calc(var(--of-bevel-width) * 2) solid var(--of-color-focus);
    outline-offset: var(--of-space-tightest);
  }

  .tile-set {
    font-size: var(--of-type-size-micro);
    max-inline-size: var(--of-card-face-thumb);
    text-align: center;
  }

  .tile-id {
    font-size: var(--of-type-size-micro);
    letter-spacing: var(--of-type-tracking-wide);
    text-transform: uppercase;
    color: var(--of-color-ink-faint);
  }
</style>

// apps/site/ssg/islands/PrintingPicker.tsx
/**
 * The alternate printings of one card, as a picker that swaps the face. React
 * port.
 *
 * NAMED BY SET AND NUMBER, because `BEN010` alone answers "which printing" for
 * somebody who already knows the set codes and nobody else. "Bright Lights ·
 * BEN010" answers it for everybody, and the number is kept because it is the
 * citable identity of a printing.
 *
 * WHY THIS IS AN ISLAND WHEN ALMOST NOTHING HERE IS. `docs/SCRYFALL-GAP.md` §5.2
 * rules out live updating for SEARCH — results must not re-rank under a cursor,
 * because the URL is the product. A printing picker is the opposite case: it
 * changes which image is displayed and nothing else. There is no query, no
 * ranking, no result set.
 *
 * THE FACE IS SWAPPED, NOT NAVIGATED, and the address bar is rewritten to the
 * printing's OWN page. Clicking a tile changes an image, so making it a link
 * would be a page load to move one picture — but the URL it writes has to be one
 * that works on its own, which is what the per-printing routes are for. The
 * address is always something the reader can copy and hand to anything at all.
 *
 * ONE SELECTION, AND IT IS A RADIO GROUP, because that is what "pick exactly one
 * of these" is. Arrow keys and a group name come free, the current choice is
 * announced rather than merely outlined, and a reader who cannot see the accent
 * border still knows which printing they are looking at.
 *
 * THE RADIOS ARE CONTROLLED, WHICH IS A PORT DIFFERENCE WITH TEETH. Svelte's
 * `checked={...}` plus `onchange` left the DOM in charge; React's `checked` makes
 * the input controlled and requires `onChange`, which is supplied. The
 * alternative — `defaultChecked` — would let the DOM and `selected` disagree the
 * moment the server-rendered index is not zero, which is exactly the case
 * per-printing URLs introduced.
 */

import { useCallback, useEffect, useId, useState } from "react";

import { CardFace, CardFaceGroup } from "optfall-components/react";

import "./PrintingPicker.css";

export interface Printing {
  /** Blob key, already resolved by the build. */
  readonly key: string;
  /** Collector number — the citable identity. Carries the edition too where set
   *  and number alone do not tell two printings apart. */
  readonly id: string;
  readonly edition: string;
  /** The set's published name, or its code where upstream names none. */
  readonly setName: string;
  readonly setCode: string;
  readonly thumb: string;
  readonly normal: string;
  readonly width: number;
  readonly height: number;
  readonly thumbWidth: number;
  readonly thumbHeight: number;
  /** This printing's own page — `/card/<slug>/<set>/<number>`. */
  readonly href: string;
}

export interface PrintingPickerProps {
  readonly printings: readonly Printing[];
  /** The accessible name for the card's picture, composed by the caller. */
  readonly alt: string;
  /** The card's label, for the group's accessible name. */
  readonly label: string;
  /** Which face the server already rendered. */
  readonly selected?: number;
}

const PARAM = "printing";

function keyOf(printing: Printing): string {
  return printing.key.replace(/\.webp$/, "");
}

export function PrintingPicker({
  printings,
  alt,
  label,
  selected: initial = 0,
}: PrintingPickerProps) {
  /**
   * WHERE THE SELECTION COMES FROM, IN PRIORITY ORDER.
   *
   * 1. The PATH, resolved by the server. A per-printing URL is a page, so by the
   *    time this runs the correct face is already in the DOM and the only right
   *    thing to do is agree with it.
   * 2. `?printing=`, for links pasted before those pages existed. The param is
   *    no longer written, but it was, and a reference tool that breaks its own
   *    old links has failed at the one thing it is for.
   *
   * READ IN AN EFFECT, NOT AT INITIALISATION, for the reason `RulesSearch`
   * records: the server has no `window`, so initialising from the URL renders a
   * different tree than the server did and hydration fails. The server already
   * rendered the right face from `selected`, so the correction only ever fires
   * for the legacy query form.
   */
  const [selected, setSelected] = useState(initial);

  const fromUrl = useCallback((): number => {
    if (typeof window === "undefined") return initial;

    const here = window.location.pathname.replace(/\/$/, "");
    const byPath = printings.findIndex(
      (printing) => printing.href.replace(/\/$/, "") === here,
    );
    if (byPath !== -1) return byPath;

    const wanted = new URLSearchParams(window.location.search).get(PARAM);
    if (wanted === null) return initial;
    const index = printings.findIndex((printing) => keyOf(printing) === wanted);
    return index === -1 ? initial : index;
  }, [initial, printings]);

  useEffect(() => {
    const next = fromUrl();
    if (next !== initial) setSelected(next);
  }, [fromUrl, initial]);

  /** Back and forward have to work, which means listening for them. */
  useEffect(() => {
    const onPop = () => setSelected(fromUrl());
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  }, [fromUrl]);

  const current = printings[selected] ?? printings[0];
  const uid = useId();

  /**
   * `replaceState`, not `pushState`.
   *
   * Clicking through six printings should not put six entries in the back
   * button — the reader is looking at one card, not visiting six pages. The
   * address stays correct so it can be copied at any moment, and Back still
   * returns to wherever they came from.
   */
  function remember(index: number): void {
    setSelected(index);
    const printing = printings[index];
    if (printing === undefined || typeof window === "undefined") return;
    window.history.replaceState({}, "", printing.href);
  }

  if (current === undefined) return null;

  return (
    /*
      EVERY FACE HERE GOES THROUGH THE COMPONENT, thumbnails included. An earlier
      version rendered the tiles as bare `<img>` tags, which is the exact path
      docs/COMPLIANCE.md §5 names as a way to break the copyright condition — and
      it left 22 card images on a page under one notice.

      The group carries the notice for all of them, once, because these are
      several pictures of ONE card and the legal fact is the same for each.
    */
    <CardFaceGroup>
      <div className="of-picker">
        <CardFace
          src={current.normal}
          alt={alt}
          width={current.width}
          height={current.height}
          loading="eager"
        />

        {printings.length > 1 ? (
          <fieldset className="of-picker__rail">
            <legend className="of-picker__legend">Printings of {label}</legend>
            <ul className="of-picker__list">
              {printings.map((printing, index) => (
                <li key={printing.key}>
                  <label
                    className={
                      index === selected
                        ? "of-picker__tile of-picker__tile--current"
                        : "of-picker__tile"
                    }
                  >
                    <input
                      type="radio"
                      name={`${uid}-printing`}
                      checked={index === selected}
                      onChange={() => remember(index)}
                    />
                    <span className="of-picker__face">
                      <CardFace
                        src={printing.thumb}
                        alt=""
                        width={printing.thumbWidth}
                        height={printing.thumbHeight}
                      />
                    </span>
                    <span className="of-picker__set">{printing.setName}</span>
                    <span className="of-picker__id">{printing.id}</span>
                  </label>
                </li>
              ))}
            </ul>
          </fieldset>
        ) : null}
      </div>
    </CardFaceGroup>
  );
}
