// apps/site/src/components/RandomCard.svelte
<script lang="ts">
  /**
   * Picks a card and goes there.
   *
   * `Math.random()` is the whole implementation, and that is the point: there
   * is nothing to rank, nothing to weight and nothing to remember. A "random"
   * that avoided repeats would need state, and state on a static site is a
   * cookie nobody asked for.
   *
   * It navigates on mount rather than offering a button, because the reader
   * already pressed the button — it was the link that brought them here.
   */
  import { decodeNameIndex, type EncodedNameIndex } from "../lib/typeahead";

  interface Props {
    index: EncodedNameIndex;
  }

  const { index }: Props = $props();

  const names = $derived(decodeNameIndex(index));

  let href = $state<string | null>(null);

  $effect(() => {
    if (names.size === 0) return;
    const pick = Math.floor(Math.random() * names.size);
    const slug = names.slugs[pick];
    if (slug === undefined) return;
    href = `/card/${slug}`;
    window.location.replace(href);
  });
</script>

<!--
  A link, not just a redirect. If the navigation is blocked or slow the reader
  still has something to press, and `replace` keeps the back button pointing at
  wherever they came from rather than trapping them in a loop of random cards.
-->
<p class="fallback">
  {#if href}
    <a href={href}>Opening a card…</a>
  {:else}
    Choosing a card…
  {/if}
</p>

<style>
  .fallback {
    color: var(--of-color-ink-muted);
  }
</style>

// apps/site/ssg/islands/RandomCard.tsx
/**
 * Picks a card and goes there. React port.
 *
 * `Math.random()` is the whole implementation, and that is the point: there is
 * nothing to rank, nothing to weight and nothing to remember. A "random" that
 * avoided repeats would need state, and state on a static site is a cookie
 * nobody asked for.
 *
 * It navigates on mount rather than offering a button, because the reader
 * already pressed the button — it was the link that brought them here.
 *
 * THE EFFECT RUNS ONCE, WHICH IS A CHANGE FROM SVELTE AND A NECESSARY ONE.
 * Svelte's `$effect` re-ran when `names` changed, which for a prop that never
 * changes meant "once". React's dependency array has to say so explicitly, and
 * saying `[names]` here would be worse than wrong: `decodeNameIndex` returns a
 * fresh object each call, so under React's Strict Mode double-invoke the
 * component would pick a card, navigate, and pick a different card.
 */

import { useEffect, useMemo, useState } from "react";

import {
  decodeNameIndex,
  type EncodedNameIndex,
} from "../../src/lib/typeahead";

import "./RandomCard.css";

export interface RandomCardProps {
  readonly index: EncodedNameIndex;
}

export function RandomCard({ index }: RandomCardProps) {
  const names = useMemo(() => decodeNameIndex(index), [index]);
  const [href, setHref] = useState<string | null>(null);

  useEffect(() => {
    if (names.size === 0) return;
    const pick = Math.floor(Math.random() * names.size);
    const slug = names.slugs[pick];
    if (slug === undefined) return;
    const target = `/card/${slug}`;
    setHref(target);
    window.location.replace(target);
  }, [names]);

  return (
    /*
      A link, not just a redirect. If the navigation is blocked or slow the
      reader still has something to press, and `replace` keeps the back button
      pointing at wherever they came from rather than trapping them in a loop of
      random cards.
    */
    <p className="of-random__fallback">
      {href ? <a href={href}>Opening a card…</a> : "Choosing a card…"}
    </p>
  );
}
